name: xdm-visualization
on:
  push:
jobs:
  xdm-visualization:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.13'
      - run: npm install
      - run: ./bin/visualBuild.sh

